version: 2
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
#    - go mod tidy
#    - go mod vendor
builds:
- env:
    - CGO_ENABLED=0
    - GO111MODULE=on
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - "386"
    - amd64
    - arm
    - arm64
    - mips64
    - mips64le
    - mips
    - mipsle
  gomips:
    - hardfloat
    - softfloat
  ignore:
    - goos: darwin
      goarch: "386"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
snapcrafts:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    summary: OpenIoTHub Server.
    description: |
      OpenIoTHub Server
    grade: stable
    confinement: strict
#    confinement: classic
    publish: true
    apps:
      server-go:
        plugs: ["network", "network-bind"]
        daemon: simple
dockers:
  - image_templates:
      - 'openiothub/server-go:{{ .Tag }}'
      - 'openiothub/server-go:v{{ .Major }}.{{ .Minor }}'
      - 'openiothub/server-go:latest'
    dockerfile: Dockerfile
    use: buildx
#    binaries:
#      - server-go
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=com.github.actions.name={{.ProjectName}}"

    extra_files:
      - scripts/entrypoint.sh